#!/usr/bin/python

import sys
import os.path
import subprocess

def init():
    args = sys.argv[1:]
    valid_args = True
    
    if len(args) < 2:
        valid_args = False
        print "Usage: ./answer <path/to/article> <number-of-questions>"
        sys.exit(-1) 
    
    if not os.path.isfile(args[0]):
        valid_args = False
        print args[0], "is not a valid file"
   
    try:
        nquestions = int(args[1])
        if nquestions <= 0:
            valid_args = False
            print args[1], "is not a valid positive integer"
            
    except ValueError:
        valid_args = False
        print args[1], "is not a valid positive integer"
        
    if valid_args:
        return args[0], int(args[1])
    else:
        sys.exit(1)

article_path, nquestions = init()
cmd = './scripts/run.sh question-asker --debug 2>/dev/null < %s' % article_path

output = subprocess.check_output(cmd, shell=True)

questions = []

for line in output.split('\n'):
  if line.strip() == '':
    continue
  
  question, sentence, answer, score = line.strip().split('\t')
  questions.append(question)
  
print '\n'.join(questions[0:min(len(questions), nquestions)])





